services:
  apache:
    container_name: 'tygo-van-den-hurk.com-apache-container'
    image: httpd:alpine
    restart: always
    networks:
      - 'proxymesh'
      - 'default'
    volumes:
      - "${PWD}/html/:/usr/local/apache2/htdocs/"
      - "${PWD}/config/httpd.conf:/usr/local/apache2/conf/httpd.conf"
networks:
  proxymesh:
    external: true
